apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.46.101.86.85.nip.io/root/k3d_ael-korc_conf.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true 