apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-cluster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/moelazhari/mazhari
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      selfHeal: true
      prune: true