# -*- mode: ruby -*-
# vi: set ft=ruby :
pubkey = File.readlines(File.expand_path("~/.ssh/id_rsa.pub")).first.strip
Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20230607.0.5"
  
  config.vm.define "ael-korcS" do |master|

    
    master.vm.provider "virtualbox" do |vb|
      vb.name = "ael-korcS"
      vb.cpus = 2
      vb.memory = 1024
    end
    
    master.vm.network "private_network", ip: "192.168.56.110"
    
    master.vm.hostname = "ael-korcS"
    
    master.vm.provision "shell", path: "./scripts/setupS.sh", args: [pubkey]
    
  end

  config.vm.define "ael-korcSW" do |worker|

    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ael-korcSW"
      vb.cpus = 2
      vb.memory = 1024
    end

    
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.hostname = "ael-korcSW"

    worker.vm.provision "shell", path: "./scripts/setupSW.sh", args: [pubkey]
  end

end
