ENV["LC_ALL"] = "en_US.UTF-8"

NODES = {
  'mazhariS' => {
    ip: '192.168.56.110',
    hostname: 'mazhariS',
    role: 'server',
    provider: {
      name: 'virtualbox',
      memory: 1024,
      cpus: 2,
    }
  },
  'mazhariSW' => {
    ip: '192.168.56.111',
    hostname: 'mazhariSW',
    role: 'agent',
    provider: {
      name: 'virtualbox',
      memory: 512,
      cpus: 1,
    }
  },
}

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"

  NODES.each do |name, machine|
    config.vm.define name do |node|
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]

      node.vm.provider machine[:provider][:name] do |vb|
        vb.name = name
        vb.memory = machine[:provider][:memory]
        vb.cpus = machine[:provider][:cpus]
      end

      node.vm.provision "shell", inline: <<-SHELL
        sudo apk update 
        sudo apk add curl
      SHELL

      if machine[:role] == 'server'
        node.vm.provision "shell", path: "scripts/install_k3s_server.sh"
      elsif machine[:role] == 'agent'
        node.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
      end
    end
  end
  
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
